apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar_v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstar_v1
  template:
    metadata:
      labels:
        app: hotstar_v1
    spec:
      containers:
      - name: hotstar_v1
        image: roshinikonda/hotstar:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: hotstar_v1-service
spec:
  selector:
    app: hotstar_v1
  ports:
    - protocol: TCP
      port: 80         # Exposes on port 80
      targetPort: 3001 # Maps to containerPort
  type: LoadBalancer   # Or NodePort for non-cloud
